<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.12 floorStones.glb -T
-->

<script>
    import { Group } from 'three'
    import { T, forwardEventHandlers } from '@threlte/core'
    import { useGltf, InstancedMeshes } from '@threlte/extras'
    import seedrandom from 'seedrandom'

    export const ref = new Group()

    const gltf = useGltf('/objects/stone_brick-transformed.glb', { useDraco: true })

   // const component = forwardEventHandlers()

    let sRandom = seedrandom('seed14')

    const rotationValues = [0, 3.14159]

    const items = Array.from({ length: 21 }, () => ({
        x: sRandom() * 18 - 9,
        z: sRandom() * 7 - 3,
        scale: 0.1,
        rotation: {
            x: 0,
            y: Math.floor(sRandom() * 2),
            z: 0
        }
    }))
</script>

{#await gltf}
    <slot name="fallback" />
{:then gltf}
    <InstancedMeshes meshes={gltf.nodes} let:components={{ Mesh }} name={'floor stones'} castShadow receiveShadow>
        <T.MeshToonMaterial color="#585858" />
        {#each items as item}
            <Mesh
                position.y={0}
                position.z={item.z}
                position.x={item.x}
                scale={[0.3, 0.05, 0.3]}
                rotation.y={rotationValues[item.rotation.y]}
                rotation.x={0}
                rotation.z={0}
            />
        {/each}
    </InstancedMeshes>
{:catch error}
    <slot name="error" {error} />
{/await}

<slot {ref} />
