<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.12 blue.glb --transform
-->

<script>
    import { Group } from 'three'
    import { T, forwardEventHandlers } from '@threlte/core'
    import { useGltf, useGltfAnimations } from '@threlte/extras'
    import { Vector3, Matrix4, Euler, Quaternion } from 'three';

    export const ref = new Group()

    //const currentPosition = new Vector3(position.x,0,position.z);
    let x = Math.random() * 10


    const gltf = useGltf('/blue-transformed.glb?v='+x, { useDraco: true })

    async function loaded(){
        await gltf;
        console.log(x)

    }

    loaded()
    //export const { actions, mixer } = useGltfAnimations(gltf, ref)

    const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Scene">
      <T.Group name="Armature" scale={0.01}>
        <T is={gltf.nodes.mixamorigHips} />
        <T.SkinnedMesh
          name="Beta_Joints"
          geometry={gltf.nodes.Beta_Joints.geometry}
          material={gltf.materials['Beta_Joints_MAT.002']}
          skeleton={gltf.nodes.Beta_Joints.skeleton}
        />
        <T.SkinnedMesh
          name="Beta_Surface"
          geometry={gltf.nodes.Beta_Surface.geometry}
          material={gltf.materials['asdf1:Beta_HighLimbsGeoSG2.001']}
          skeleton={gltf.nodes.Beta_Surface.skeleton}
        />
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
