<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.12 girl.glb -T
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'
  import { toonMaterial } from '$lib/util/toonMaterial'

  export const ref = new Group()

  const gltf = useGltf('/girl.glb', { useDraco: true })
  export const { actions, mixer } = useGltfAnimations(gltf, ref)

  const component = forwardEventHandlers()

  const material = new toonMaterial( "/girl.png" ).material

  let currentActionKey = "run"

  $: $actions[currentActionKey]?.play();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Scene">
      <T.Group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.005}>
        <T is={gltf.nodes.mixamorigHips} />
        <T.SkinnedMesh
          name="Cylinder005"
          geometry={gltf.nodes.Cylinder005.geometry}
          material={material}
          skeleton={gltf.nodes.Cylinder005.skeleton}
        />
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
