<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.12 tech_wall.glb -T
-->

<script lang="ts">
    import { Group } from 'three'
    import { T, forwardEventHandlers } from '@threlte/core'
    import { useGltf, InstancedMesh, Instance } from '@threlte/extras'
    
    export let url : string

    const gltf = useGltf(url, { useDraco: true })
</script>

{#await gltf then gltf}
  <T.Mesh {...$$restProps} geometry={gltf.nodes.Mesh.geometry} />
{/await}
