<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.12 tech_wall.glb -T
-->

<script lang="ts">
    import { Group } from 'three'
    import { T, forwardEventHandlers } from '@threlte/core'
    import { useGltf, InstancedMesh, Instance } from '@threlte/extras'
    
    export let url : string
    export let scale :  [x: number, y: number, z: number]
    export let instances: {
        position?: [x: number, y: number, z: number],
        rotation?: [x: number, y: number, z: number]
    }[] = [{ position: [0, 0, 0], rotation: [0, 0, 0] }]

    const gltf = useGltf(url, { useDraco: true })
</script>

{#await gltf then gltf}
    <InstancedMesh castShadow receiveShadow {...$$restProps} geometry={gltf.nodes.Mesh.geometry}>
        <T.MeshStandardMaterial />
        {#each instances as object}
            <Instance position={object.position} rotation={object.rotation} scale={scale} />
        {/each}
    </InstancedMesh>
{/await}
