<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.12 rock.glb
-->

<script>
    import { Group } from 'three'
    import { T, forwardEventHandlers } from '@threlte/core'
    import { useGltf, InstancedMeshes } from '@threlte/extras'
    import seedrandom from 'seedrandom'

    export const ref = new Group()

    const gltf = useGltf('/rock.glb')

    const component = forwardEventHandlers()

    let sRandom = seedrandom('seed')

    const items = Array.from({ length: 120 }, () => ({
        x: sRandom() * 75 - 37.5,
        z: sRandom() * 75 - 37.5,
        scale: sRandom() * 0.01 + 0.1,
        rotation: {
            x: sRandom() * 360,
            y: sRandom() * 360,
            z: sRandom() * 360
        }
    }))
    
</script>

{#await gltf}
    <slot name="fallback" />
{:then gltf}
    <InstancedMeshes meshes={gltf.nodes} let:components={{ Rock }} castShadow receiveShadow>
        <T.MeshToonMaterial color="#ac6130" />
        {#each items as item}
            <Rock
                position.y={0}
                position.z={item.z}
                position.x={item.x}
                scale={[0.12, 0.12, 0.12]}
                rotation.y={(item.rotation.y * Math.PI) / 180}
                rotation.x={(item.rotation.x * Math.PI) / 180}
                rotation.z={(item.rotation.z * Math.PI) / 180}
            />
        {/each}
    </InstancedMeshes>
{:catch error}
    <slot name="error" {error} />
{/await}
