<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.12 rock.glb
-->

<script>
    import { Group } from 'three'
    import { T, forwardEventHandlers } from '@threlte/core'
    import { useGltf, InstancedMeshes } from '@threlte/extras'
    import seedrandom from 'seedrandom'
    import { onMount } from 'svelte'

    export const ref = new Group()

    const gltf = useGltf('/objects/desert_rock-transformed.glb', { useDraco: true })

    const component = forwardEventHandlers()

    let sRandom = seedrandom('seed')

    const items = Array.from({ length: 120 }, () => ({
        x: sRandom() * 80 - 40,
        z: sRandom() * 80 - 40,
        scale: sRandom() * 0.25 + 0.15,
        rotation: {
            x: sRandom() * 360,
            y: sRandom() * 360,
            z: sRandom() * 360
        }
    }))

    
</script>

{#await gltf}
    <slot name="fallback" />
{:then gltf}
    <InstancedMeshes meshes={gltf.nodes} let:components={{ Mesh }} castShadow receiveShadow>
        <T.MeshToonMaterial color="#9c5b30" />
        {#each items as item}
            <Mesh
                position.y={0}
                position.z={item.z}
                position.x={item.x}
                scale={item.scale}
                rotation.y={(item.rotation.y * Math.PI) / 180}
                rotation.x={(item.rotation.x * Math.PI) / 180}
                rotation.z={(item.rotation.z * Math.PI) / 180}
            />
        {/each}
    </InstancedMeshes>
{:catch error}
    <slot name="error" {error} />
{/await}
