<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.12 ship.glb --transform
-->

<script lang="ts">

    import { gameMessage } from "$lib/stores"
    import { Group } from 'three'
    import { T, forwardEventHandlers } from '@threlte/core'
    import { useGltf } from '@threlte/extras'
    import { useCursor } from "$lib/useCursor"

    export const ref = new Group()

    
    const gltf = useGltf('/ship-transformed.glb', { useDraco: true })
    const component = forwardEventHandlers()
    const { onPointerEnter, onPointerLeave } = useCursor()

    function clicked(e : any){
        $gameMessage = 'Your ship'
    }

</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}  on:click={(e) => {e.stopPropagation(); clicked(e)}}  >
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
        on:pointerenter={onPointerEnter} 
        on:pointerleave={onPointerLeave}
        castShadow
        geometry={gltf.nodes.Striker.geometry}
        material={gltf.materials['Texture.002']}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
