<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.12 spaceship.glb -T
-->

<script>
    import { Group, SRGBColorSpace } from 'three'
    import { T, forwardEventHandlers } from '@threlte/core'
    import { useGltf, useTexture } from '@threlte/extras'

    export const ref = new Group()

    const gltf = useGltf('/objects/spaceship-transformed.glb', { useDraco: true })
    const texture = useTexture('/texture/shipAtlas.png')

    const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
    {#await gltf}
        <slot name="fallback" />
    {:then gltf}
        <T.Mesh
            castShadow
            geometry={gltf.nodes.Mesh.geometry}           
            position={[-2.42, 0.06, 0]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[0.46, 0.86, 0.46]}
        >
            {#await texture then t}
                <T.MeshToonMaterial color="#ffffff">
                    <T is={t} attach="map" flipY={false} colorSpace={SRGBColorSpace} />
                </T.MeshToonMaterial>
            {/await}
        </T.Mesh>
    {:catch error}
        <slot name="error" {error} />
    {/await}

    <slot {ref} />
</T>
