<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.13 tech_sign.glb -T
-->

<script lang="ts">
    import { Group, ShaderMaterial, SkinnedMesh } from 'three'
    import { T, forwardEventHandlers } from '@threlte/core'
    import { useGltf } from '@threlte/extras'
    import HolgramMaterial from '../materials/HolgramMaterial.svelte'

    export const ref = new Group()

    const gltf = useGltf('/objects/tech_sign-transformed.glb', { useDraco: true })
    //const gltf = useGltf('/objects/hologram-transformed.glb', { useDraco: true })

    const component = forwardEventHandlers()

</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
    {#await gltf}
        <slot name="fallback" />
    {:then gltf}
        <T.Mesh geometry={gltf.nodes.Mesh.geometry}  >
            <HolgramMaterial />
        </T.Mesh>
    {:catch error}
        <slot name="error" {error} />
    {/await}

    <slot {ref} />
</T>